[package]
name = "base16"
version = "0.2.1"
authors = ["Thom Chiovoloni <chiovolonit@gmail.com>"]
keywords = ["hex", "base16", "encode", "decode", "no_std"]
repository = "https://github.com/thomcc/rust-base16"
description = "base16 (hex) encoding and decoding"
categories = ["encoding", "no-std"]
license = "CC0-1.0"
readme = "README.md"
edition = "2018"

[features]
std = ["alloc"]
alloc = []
default = ["std"]

[dependencies]

[dev-dependencies]
rand = "0.8.5"
divan = "0.1.14"

[[bench]]
name = "bench"
harness = false

[package.metadata.docs.rs]
all-features = true
